# Generated by Django 5.1 on 2024-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('_texto', models.TextField(max_length=200)),
                ('_fecha', models.DateField()),
            ],
        ),
    ]
