# Generated by Django 5.1 on 2024-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listatareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
