# Generated by Django 5.1 on 2024-08-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listatareas', '0002_alter_tarea__codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
