# Generated by Django 5.1 on 2024-08-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listatareas', '0003_delete_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('_titulo', models.CharField(max_length=100)),
                ('_descripcion', models.TextField(max_length=200)),
                ('_fecha', models.DateField()),
            ],
        ),
    ]
