# Generated by Django 5.1 on 2024-08-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listatareas', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
